language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
r:
- 3.2
- 3.3
- 3.4
- release
- devel
allow_failures:
- r: devel
- os: osx
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- export rver=`r_version`;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- jags_install
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" || "${PACKAGE_NAME}" == "Rvision" ]]; then
  shopt -s expand_aliases ; x=`Rscript -e "cat(Sys.which('R'))"` ; alias R="travis_wait
  100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: cjySOE83hWtYPJCSDrC/2cXQpqI7Of/xYftnK/LwUSIi2eK4FdwCDw168S1K9cUDsEXFwFoVXtMHEPmom6rjIWUQFZdE44fUsjxQlSJJdwOg9mM9GXqxvln59jBnYr4QDakyAIZJhItsTkkJ6ykkFXN8VkLa3/YDPgV5//m40Vk4VxqTxCpW0l9yoNnpmzNONLvMnznErXl5yBJ4i4REFnvPhQvlTdJygKZK/g/Ce7SFE0Djna6fzbYOQLPFYkY7ngAcKHpl8CnYazP1/rhDTGGwn7cc4zD5ewwR0Suf3BJE4pg4DVSD2KTDihYmY7XP0/aUchgWeC+VxaVE43ozrO1nVaWM1xRwi7RjoWknvrTB53JuBk5LENhNCHTgH8Jf0i2Xw+QPlNu24UP65zo2yj3p0el3hQvGHgD8IjkLFaEnn65E+GrjcwdhxBXLKkb6QoWos2eimQcwWT90LyYaAQ1E7DBcVr3lwWhXTff+TM0fGcHV0ICrwfP+wW/sJLLLbYhtHvyz1Fy3vzUoNkNPWqK/XcaKd1oRmM5KAvdnek45zvPcanDM4oBfzVT8fFoj2M2n6QmPlpkG6sumGwP0FaRP6YmdD1UknV9E6O4uWO1v9hgSvPN8eEbydYMmLdWmnd0OAwCN4BrwbCHBNwipbJoxXde6rIoUNiauA1RHfqA=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" ]];
  then echo 'covr::coveralls(type = "all")' > neuroc_covr.R ; travis_wait 100 Rscript
  neuroc_covr.R ; rm neuroc_covr.R ; fi
