language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" ]]; then shopt -s expand_aliases ; x=`Rscript
  -e "cat(Sys.which('R'))"` ; alias R="travis_wait 100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: ZwUOXds35bFJcOMIJGRux1DnZIvIC9XwY33nj5iek492ndorNtEWi6bH9KztrKN2R3ZNleAF8pbL6ulog+gQjQtCrsUJGi0cBSawehzE8Axr3ZLVH3oF2JQDTBpZDrwt9tIIluj24i02927A20GgEXKSpw46dEy9mw0BNRYKxmx6tMI+QuuX/B9RZUDAvtODSUy4TR4fUoW+R3UKfe6vbU394EF4vDdOFNWUjO65ORxLnOsReLjZxl9Lt3b+vzOQeC4WpjOlgE8GloxzRyxaXuzDY0IoM9LZvWc0pwaQB4qNcQJkR/VHtjhFbpTQclxx2osaV8GkeNPjF+lpT2v5nKWFdBpYbT92EvcyXBF9/f4Dw9aKXdRsTJMMx4B6y5A0t3UgxC8aSBF3uColFQdCO/9RkWHY0Evjv6t0qigKIxWJaobo1ujG5q3kMXTvkZI9oWQnlAlbgCE75iieuSvutTXv6Syr7dDtL3aByEACjtUPg7kf/Q05sMsdKiremvQQ6YaTYHbkgUcXbnAgd21WOBx+yiqWGXHDsFs6Sj8cQ/+IkonQNow+hh6xwawKB7pw4ds9we4wRVg7HMLuJltzN4tbbXE3t9RxlgjrMJZh0ex7UpEGAQJPe/LjnNboNmIavfifMDN/JaUzWWfEu0MAihoWkDYDtUVE1NBPw79rwvo=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo 'covr::coveralls(type = "all")'
  > neuroc_covr.R ; travis_wait 100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
