language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
r:
- 3.2
- 3.3
- 3.4
- release
- devel
allow_failures:
- r: devel
- os: osx
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- export rver=`r_version`;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- jags_install
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" || "${PACKAGE_NAME}" == "Rvision" ]]; then
  shopt -s expand_aliases ; x=`Rscript -e "cat(Sys.which('R'))"` ; alias R="travis_wait
  100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: PH37bMUUj9AdIfXP+6ObDHu3ujFBpTSGLpSNMu1OkkeOXnr6WxkfI8vNi6mRHeiYQQkhx6UKBQUnhfWmzXSzPvEYNeTxVa+CrTDVEnvicw2KQbNmdYwUfDDqUtRVyxGi6zPyqiyav70V6WU1HGXs34jx2BFkr7mtOSeqVFGthFV6HqMrtr6mOxeY0U7kVWx0MbJEN3IZeF8NKw5V+6hSUPZIiIBEjdumftvbZzEum61BULlkcBwNSQa1ep09Hgi/CUAHeKuVSglj5iLmKgu5QXlLiRgIm7acnGHqZCRdK5NFvmdJxxx+2TAc31OukVfhVjVYAKpKNhU8giVWC8r3PabSavIbw8HB00ookcg+9dCVXHwnkqe1g/7HWAOSvZtadmH2+U6T98kWfvvjGCASckdb6L/f6rjNNHzr7eOLyKDXtsztup1w1GimJ5El8nuXTjqjJFhM/8MCTelkmWfioCcsjd0Szv8gnM/cFz6EU20taKH0HqQuHqcRQdxQgLvBuKkmKIIvmZEgzOPvl4pKG1HMg0K1U4AqsYHYXW23apLllSKMH6lVIczqiAsdeSYwYlmJ+RTPHw9pc1K3PqtgMAmDw9KyLTx0w6n5ZWWcjCT9727xbWgcFDjGBalsfGPgx3W3jd6bdj/T3wXRY3NX59XSiydZrIrq7O3YjlMdB/Y=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" ]];
  then echo 'covr::coveralls(type = "all")' > neuroc_covr.R ; travis_wait 100 Rscript
  neuroc_covr.R ; rm neuroc_covr.R ; fi
